### ISSUE TITLE
Pager.rb file

### ISSUE THREAD

**Issue by fordmadox** [archivesspace/public-new#1]
Just in case you don't see this on JIRA:

The "next" link is no longer going up by 6, but it's not working consistently since it's pretty much always going down, save for when you use "next" on pages 1 or 2 (perhaps the current "page" parameter isn't always available?). In any event, here's what happens:
- At page 1, clicking on next goes to page 2. (this is the one case where it's working as expected)
- Now at page 2, clicking on next stays right on page 2 (if I go to pages 3 - 5, clicking next goes to page 2)
- If I click on another page, such as page 6, clicking on next goes to page 2 (at pages 6 and up, next is always -4 from the current page)
- If I click a bit higher, on page 7, to get the previous link to show up, and then click on previous, I go to page 1 (not page 6, which would be expected).
- If I go to page 8 and click previous, I'm taken to page 2. So, same behavior of -6 with the previous link.

**Comment by bobbi-SMR** [comment]
I believe I've fixed this.
